# --- App Configuration ---
APP_NAME = "Otter Voice"
APP_ICON_FILENAME = 'image__2__o6e_icon.ico'
INITIAL_WINDOW_WIDTH = 550
INITIAL_WINDOW_HEIGHT = 335
DEV_MODE_HEIGHT_INCREASE = 300

# --- Font Configuration ---
DESIRED_FONT_FAMILY = "思源黑体"
DESIRED_FONT_FILENAME = "SourceHanSansSC-Regular.otf"
DEFAULT_FALLBACK_FONT = "Roboto"
FONT_SIZE_LABEL = 13
FONT_SIZE_TEXTBOX = 11
FONT_SIZE_STATUS = 12
FONT_SIZE_TITLE = 22

# --- Sound Files ---
SOUND_CALL_CONNECTED = "notification_call.wav"
SOUND_PEER_HANGUP = "notification_hangup.wav"

# --- UI Colors ---
COLOR_TEXT_DEFAULT = ("#FFFFFF", "#FFFFFF")
COLOR_TEXT_MUTED = ("gray50", "gray50")
COLOR_STATUS_DEFAULT = ("gray60", "gray40")
COLOR_STATUS_INFO = ("#1E88E5", "#42A5F5")
COLOR_STATUS_SUCCESS = ("#43A047", "#66BB6A")
COLOR_STATUS_WARNING = ("#FFA000", "#FFCA28")
COLOR_STATUS_ERROR = ("#D32F2F", "#EF5350")
COLOR_STATUS_CALLING = ("#FF8C00", "#FFA500")
COLOR_BUTTON_CALL_FG = ("#FFFFFF", "#FFFFFF")
COLOR_BUTTON_ACCEPT_BG = ("#4CAF50", "#66BB6A")
COLOR_BUTTON_REJECT_BG = ("#F44336", "#EF5350")
COLOR_BUTTON_ACCEPT_HOVER_BG = ("#409443", "#59A85C")
COLOR_BUTTON_REJECT_HOVER_BG = ("#D32F2F", "#D73F3F")
PACKET_INDICATOR_GREEN_ACK = "#00FF00"
PACKET_INDICATOR_RED_SENT = "#FF0000"
PACKET_INDICATOR_IDLE = "gray50"

# --- Network Configuration ---
DEFAULT_STUN_HOST = 'stun.miwifi.com'
DEFAULT_STUN_PORT = 3478
FEATURE_CODE_KEY = "P2PKey!VoIP"
MAX_PACKET_SIZE = 4096
RANDOM_PORT_START = 49152
RANDOM_PORT_END = 65535
RANDOM_PORT_MAX_TRIES = 100

# --- Call Logic Timings ---
CALL_REQUEST_ACK_TIMEOUT_MS = 500
HANGUP_ACK_TIMEOUT_MS = 500
CALL_END_UI_RESET_DELAY_MS = 3000

# --- Audio Configuration ---
import pyaudio
PYAUDIO_FORMAT = pyaudio.paInt16
PYAUDIO_CHANNELS = 1
PYAUDIO_RATE = 40000
PYAUDIO_CHUNK = 256
MAX_SEQ_NUM = 2**32
SEQ_NUM_DEQUE_MAXLEN = 200
MIC_READ_MAX_ERRORS = 20

# --- Status Messages ---
STATUS_WAITING_FOR_REMOTE_INFO = "未有远端特征/已可接收呼叫"
STATUS_READY_TO_CALL_OR_RECEIVE = "已可发出呼叫/已可接收呼叫"
STATUS_SENDING_CALL_REQUEST = "正在发送呼叫请求..."
STATUS_LOCALLY_HUNG_UP = "已主动挂断"
STATUS_PEER_HUNG_UP = "对方已挂断"
STATUS_PEER_REJECTED = "对方已拒绝"