from enum import Enum, auto

class AppState(Enum):
    STARTING = auto()
    INITIALIZING_NETWORK = auto()
    GETTING_PUBLIC_IP_FAILED = auto()
    IDLE = auto()
    CALL_INITIATING_REQUEST = auto()
    CALL_OUTGOING_WAITING_ACCEPTANCE = auto()
    CALL_INCOMING_RINGING = auto()
    IN_CALL = auto()
    CALL_TERMINATING_SELF_INITIATED = auto()
    CALL_REJECTING = auto()
    CALL_ENDED_LOCALLY_HUNG_UP = auto()
    CALL_ENDED_PEER_HUNG_UP = auto()
    CALL_ENDED_PEER_REJECTED = auto()
    CALL_ENDED_ERROR = auto()
    CALL_ENDED_REQUEST_FAILED = auto()
    CALL_ENDED_APP_CLOSING = auto()

class SignalType(Enum):
    HANGUP_SIGNAL = b"__VOICE_CHAT_HANGUP__"
    CALL_REQUEST_SIGNAL_PREFIX = b"__CALL_ME_PLEASE__:"
    CALL_ACCEPTED_SIGNAL = b"__CALL_ACCEPTED__"
    ACK_CALL_REQUEST_SIGNAL = b"__ACK_CALL_REQUEST__"
    ACK_HANGUP_SIGNAL = b"__ACK_HANGUP__"
    SPEAKER_STATUS_SIGNAL_PREFIX = b"__SPEAKER_STATUS__:"